# Generated by Django 6.0.4 on 2026-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.FloatField(db_index=True)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('lng', models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='api_fuelsta_lat_eb8e60_idx')],
            },
        ),
    ]
